  
on: [push]

jobs:
  k6_local_test:
    name: build electron app for macos
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm
        run: brew install npm

      - name: Install yarn
        run: brew install yarn

      - name: Yarn
        run: yarn

      - name: build electron
        run: yarn dist:dir

      - name: list build dir
        run: ls dist

      - uses: actions/upload-artifact@v2
        with:
          name: electron-quick-mac.zip
          path: dist\electron-webpack-quick-start-0.0.0-mac.zip