  
on: [push]
  branches: 
    - windows

jobs:
  k6_local_test:
    name: build electron app for win
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn
        run: yarn

      - name: build electron
        run: yarn win

      - name: list build dir
        run: dir dist
      
      - uses: actions/upload-artifact@v2
        with:
          name: electron-quick-win.zip
          path: dist\electron-webpack-quick-start-0.0.0-win.zip